-- FECHA_CREACION_CONSULTA

INSERT INTO EMPRESA VALUES ('123456', 'Mi Empresa SA', 'miempresa@gmail.com', 'Avda Italia 1234', 'Juan Perez', '099334455');

INSERT INTO ESPECIALIDAD (DESCRIPCION) VALUES ('Funcional');

INSERT INTO TIPO_CONSULTA (DESCRIPCION, ID_ESPECIALIDAD) VALUES ('Repuestos', (SELECT MAX(ID) FROM ESPECIALIDAD));

INSERT INTO CONSULTA (ID_TIPO_CONSULTA, RUT_EMPRESA, DETALLE, VIA_DE_CONTACTO, TIEMPO_DE_COMUNICACION_MINUTOS)
VALUES ((SELECT MAX(ID) FROM TIPO_CONSULTA), '123456', 'Una consulta', 'Personal', 20);

-- FECHA_RESPUESTA_CONSULTA

INSERT INTO FUNCIONARIO (DOCUMENTO, TIPO, PAIS, DIRECCION, NOMBRE, FECHA_NACIMIENTO, FECHA_INGRESO)
VALUES (47338517, 'Operario', 'Uruguay', 'Cuareim 1122', 'Juan Rodriguez', '02/09/1996', '08/08/2016');

INSERT INTO RESPUESTA (DOCUMENTO_FUNCIONARIO, TEXTO, ESTADO) VALUES (47338517, 'Respuesta Generica A', 'Revisada Ok');

-- RESPUESTA_INCIDENTE

INSERT INTO CONSULTA (ID_TIPO_CONSULTA, RUT_EMPRESA, DETALLE, VIA_DE_CONTACTO, TIEMPO_DE_COMUNICACION_MINUTOS)
VALUES ((SELECT MAX(ID) FROM TIPO_CONSULTA), '123456', 'Consulta 2', 'Personal', 20);

UPDATE CONSULTA SET FECHA_CREACION = '28/11/2017' WHERE ID = 3;

INSERT INTO INCIDENTE (ID_CONSULTA, ESTADO) VALUES (3, 'Pendiente');

UPDATE CONSULTA SET ID_RESPUESTA = (SELECT MAX(ID) FROM RESPUESTA) WHERE ID = 1;

select * from INCIDENTE;

-- INDICENTE_YA_RESUELTO

INSERT INTO INCIDENTE (ID_CONSULTA, ESTADO) VALUES (3, 'Pendiente');

-- INCIDENTE_NO_LO_ES

INSERT INTO CONSULTA (ID_TIPO_CONSULTA, RUT_EMPRESA, DETALLE, VIA_DE_CONTACTO, TIEMPO_DE_COMUNICACION_MINUTOS)
VALUES ((SELECT MAX(ID) FROM TIPO_CONSULTA), '123456', 'Consulta 3', 'Personal', 20);

INSERT INTO INCIDENTE (ID_CONSULTA, ESTADO) VALUES (5, 'Pendiente');

-- RESPUESTA_ESPECIALIDAD_UNICA

INSERT INTO EMPRESA VALUES ('123456', 'Mi Empresa SA', 'miempresa@gmail.com', 'Avda Italia 1234', 'Juan Perez', '099334455');

INSERT INTO ESPECIALIDAD (DESCRIPCION) VALUES ('Funcional');
INSERT INTO ESPECIALIDAD (DESCRIPCION) VALUES ('Investigacion');

INSERT INTO TIPO_CONSULTA (DESCRIPCION, ID_ESPECIALIDAD) VALUES ('Tipo F', (SELECT ID FROM ESPECIALIDAD WHERE ESPECIALIDAD.DESCRIPCION = 'Funcional'));
INSERT INTO TIPO_CONSULTA (DESCRIPCION, ID_ESPECIALIDAD) VALUES ('Tipo I', (SELECT ID FROM ESPECIALIDAD WHERE ESPECIALIDAD.DESCRIPCION = 'Investigacion'));

INSERT INTO FUNCIONARIO (DOCUMENTO, TIPO, PAIS, DIRECCION, NOMBRE, FECHA_NACIMIENTO, FECHA_INGRESO)
VALUES (47338517, 'Operario', 'Uruguay', 'Cuareim 1122', 'Juan Rodriguez', '02/09/1996', '08/08/2016');

INSERT INTO RESPUESTA (DOCUMENTO_FUNCIONARIO, TEXTO, ESTADO) VALUES (47338517, 'Respuesta Generica A', 'Revisada Ok');

INSERT INTO CONSULTA (ID_TIPO_CONSULTA, RUT_EMPRESA, DETALLE, VIA_DE_CONTACTO, TIEMPO_DE_COMUNICACION_MINUTOS, ID_RESPUESTA)
VALUES ((SELECT ID FROM TIPO_CONSULTA WHERE DESCRIPCION = 'Tipo F'), '123456', 'Una consulta', 'Personal', 20, 1);

INSERT INTO CONSULTA (ID_TIPO_CONSULTA, RUT_EMPRESA, DETALLE, VIA_DE_CONTACTO, TIEMPO_DE_COMUNICACION_MINUTOS, ID_RESPUESTA)
VALUES ((SELECT ID FROM TIPO_CONSULTA WHERE DESCRIPCION = 'Tipo I'), '123456', 'Una consulta con otro tipo', 'Personal', 20, 1);
